"""empty message

Revision ID: 134e9e8f8dc5
Revises: 
Create Date: 2023-03-06 22:13:21.215574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134e9e8f8dc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('conta',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('limite_saque_diario', sa.Float(), nullable=True),
    sa.Column('flag_ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo_conta', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_conta')
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id_conta'], ),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('conta')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
