"""empty message

Revision ID: b410d8cd8c61
Revises: 134e9e8f8dc5
Create Date: 2023-03-08 11:22:42.461096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b410d8cd8c61'
down_revision = '134e9e8f8dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    # ### end Alembic commands ###
